env:
  browser: true
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 4
    # indentSwitchCase: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  react/jsx-uses-vars: 2
  no-console:
      - off