version: '2'

services:
    web:
        extends:
            file: services.yml
            service: web
        environment:
            - PORT='3001'

    couchdb:
        extends: services.yml
            file: services.yml
            service: couchdb
