version: '2'

services:
    web:
        extends:
            file: services.yml
            service: web
        environment:
            - PORT=3100
        ports:
            - 3100:3100
        restart: always

    couchdb:
        extends:
            file: services.yml
            service: couchdb
        restart: always
