version: '2'

services:
    web:
        build: ./dev/
        extends:
            file: services.yml
            service: web
        environment:
            - PORT=3100
        ports:
            - 3100:3100
            - 5776:5776
        volumes:
            - ./:/app/
    couchdb:
        extends:
            file: services.yml
            service: couchdb
        ports:
            - '5984:5984'
