version: '2'

services:
    web:
        extends:
            file: services.yml
            service: web
        environment:
            - PORT='3001'
        restart: always

    couchdb:
        extends:
            file: services.yml
            service: couchdb
        restart: always
